### ISSUE TITLE
Error compiling in Xcode 8.2 with swift 3.0

### ISSUE THREAD

**Issue by lawicko** [at-internet/atinternet-apple-sdk#1]
Hi, I have just tried to integrate the SmartTracker with cocoa pods:
`pod "ATInternet-Apple-SDK/SmartTracker", '1.0.3'`

Unfortunately, when building in Xcode 8.2 and swift 3.0 I get the following error:

> /Users/me/Documents/Project/myProject/Pods/ATInternet-Apple-SDK/ATInternetTracker/Sources/UILabelExtension.swift:44:17: Heterogenous collection literal could only be inferred to '[String : Any]'; add explicit type annotation if this is intentional

>

**Comment by d-theo** [comment]
Hi,

Seems that xCode8.1 and Swift3.1 transformed a warning into an error, a fix in 1.0.4 should be available soon
