### ISSUE TITLE
@objc Methods Renamings with 2 or More Parameters Miss Parameter Names

### ISSUE THREAD

**Issue by fabb** [at-internet/atinternet-apple-sdk#10]
Many of the Swift methods are renamed for Objective-C, which is a good thing. The way it's done is less than ideal, because the names of the parameters are lost at call site.

E.g.:
```
@objc(addScreenWith2Chapters:::::)
public func add(_ screenId: String, update: Date,name: String, chapter1: String, chapter2: String) -> DynamicScreen {
```

At call site this looks like this:
```
[tracker.dynamicScreens addScreenWith2Chapters:@"sid" :[NSDate date] :@"n" :@"c1" :@"c2"];
```

This does not make any sense. The renamed method signature should include a parameter name for every parameter:
```
@objc(addScreenWith2Chapters:update:name:chapter1:chapter2:)
```

Then the method call from Objective-C makes much more sense:
```
[tracker.dynamicScreens addScreenWith2Chapters:@"sid" update:[NSDate date] name:@"n" chapter1:@"c1" chapter2:@"c2"];
```

There are 20 occurrences of this problem in this library.

**Comment by d-theo** [comment]
Thanks for the feedback, we are working on it

**Comment by d-theo** [comment]
closing with the new release

**Comment by Q14** [comment]
How did you fix it，I had the same problem
