### ISSUE TITLE
2.19 minimal iOS version is not 10.0, but 12.0

### ISSUE THREAD

**Issue by kenji21** [at-internet/atinternet-apple-sdk#100]
Reviewing changes between 2.18.0 and 1.19.0, in the README.md:

https://github.com/at-internet/atinternet-apple-sdk/compare/2.18.0...2.19.0#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L7
```diff
- iOS 9.0+ or tvOS 9.0+ or watchOS 2.0
+ iOS 10.0+ or tvOS 10.0+ or watchOS 3.0
```

In the project.pbxproj https://github.com/at-internet/atinternet-apple-sdk/compare/2.18.0...2.19.0#diff-28e2745d4f477f5ea6ba3436ff6c9312aa0f57dc428fed795306e716ffe892f6L1821:

```diff

- 				IPHONEOS_DEPLOYMENT_TARGET = 9.0;
+				IPHONEOS_DEPLOYMENT_TARGET = 12.0;
```

Full changes:
https://github.com/at-internet/atinternet-apple-sdk/compare/2.18.0...2.19.0

**Comment by kenji21** [comment]
and also tvOS https://github.com/at-internet/atinternet-apple-sdk/compare/2.18.0...2.19.0#diff-28e2745d4f477f5ea6ba3436ff6c9312aa0f57dc428fed795306e716ffe892f6L1828:

```diff
-				TVOS_DEPLOYMENT_TARGET = 9.0;
+				TVOS_DEPLOYMENT_TARGET = 12.0;
```

**Comment by nsagnett** [comment]
It will be fix in the next release

Regards,

**Comment by nsagnett** [comment]
The new release available, the deployment target is 10.0 now 

Regards,

**Comment by kenji21** [comment]
hmm... can't integrate it using Xcode 11.7 and carthage :/

```
...project/Carthage/Checkouts/atinternet-apple-sdk/ATInternetTracker/Sources/TechnicalContext.swift:560:45: error: use of unresolved identifier 'CTRadioAccessTechnologyNRNSA'
                            if radioType == CTRadioAccessTechnologyNRNSA || radioType == CTRadioAccessTechnologyNR {
                                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
...project/Carthage/Checkouts/atinternet-apple-sdk/ATInternetTracker/Sources/TechnicalContext.swift:560:90: error: use of unresolved identifier 'CTRadioAccessTechnologyNR'
                            if radioType == CTRadioAccessTechnologyNRNSA || radioType == CTRadioAccessTechnologyNR {
                                                                                         ^~~~~~~~~~~~~~~~~~~~~~~~~
```

and

```
....project/Carthage/Checkouts/atinternet-apple-sdk/ATInternetTracker/Sources/Crypt.swift:33:8: error: no such module 'CryptoKit'
import CryptoKit
       ^
```

maybe GitHub actions can be integrated to prevent this (they provide multiple Xcode/iOS versions), also using SPM is the Apple way to put dependencies (saw a PR)

**Comment by nsagnett** [comment]
Hum I'm sorry for CryptoKit import...
I just pushed a new branch to fix your issues (fix/GH_100)

But, for the other one, I don't understand because there is a macro to condition this part of code only available on iOS 14

For SPM support, we don't planned to support it with this SDK version because we have functionalities which required Objective-C code and SPM doesn't like it

**Comment by kenji21** [comment]
[Realm](https://github.com/realm/realm-cocoa) is C++/Objective-C and Swift, and it is available through SPM, but separate
 in different target to have a "objc only" package, and another "swift only" package

**Comment by nsagnett** [comment]
Yes but unfortunately, it's really complicated for our different internal workflow to organize projects like that

**Comment by kenji21** [comment]
I understand, maybe shipping xcframework binaries might be a simplest way

I was using Xcode 11.7 (so deployment SDK is iOS 13.7) 

```
kenji@macboo:~/github/atinternet-apple-sdk [fix/GH_100]
export DEVELOPER_DIR=/Applications/Xcode_11.7.app/Contents/Developer/
kenji@macboo:~/github/atinternet-apple-sdk [fix/GH_100]
carthage build --no-skip-current
*** xcodebuild output can be found in /var/folders/7v/dfg0p2vj1z58n65d99l2n1lh0000gp/T/carthage-xcodebuild.s2emNa.log
*** Building scheme "Tracker iOS" in ATAnalytics.xcworkspace
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -workspace /Users/kenji/github/atinternet-apple-sdk/ATAnalytics.xcworkspace -scheme Tracker\ iOS -configuration Release -sdk iphoneos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/7v/dfg0p2vj1z58n65d99l2n1lh0000gp/T/atinternet-apple-sdk SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/kenji/github/atinternet-apple-sdk)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/7v/dfg0p2vj1z58n65d99l2n1lh0000gp/T/carthage-xcodebuild.s2emNa.log
```

**Comment by nsagnett** [comment]
Can you provide the log file just to check ?

**Comment by kenji21** [comment]
sure, here it is
[carthage-xcodebuild.s2emNa.log](https://github.com/at-internet/atinternet-apple-sdk/files/5643558/carthage-xcodebuild.s2emNa.log)

**Comment by nsagnett** [comment]
Ok `CTRadioAccessTechnologyNRNSA ` issue persists again...

Just for information, why do you compile with Xcode 11.7 ?

**Comment by kenji21** [comment]
because other dependencies doesn't build with Xcode 12 :/

**Comment by nsagnett** [comment]
Ok I see, so you can stay with 2.18.0 version for the moment and when you are ready for iOS 14 migration, you can import the latest version. 
Is it ok for you or not ?

**Comment by kenji21** [comment]
well, maybe carthage will support building xcframework at that time, otherwise i'll use this fork: https://github.com/mackoj/atinternet-apple-sdk/tree/spm_support

**Comment by nsagnett** [comment]
Well, sorry for the inconvenience
