### ISSUE TITLE
Issue for Kid category App with 2.19.0 

### ISSUE THREAD

**Issue by sebbbbbb** [at-internet/atinternet-apple-sdk#101]
Hello,

I'm working for an app which belong to the Kid category, that imply specifics policy rules for user privacy.
 
We have an issue with the last version :

In the file TechnicalContext.swift you use the macro canImport to check if AdSupport framework can be imported.
```swift
#if canImport(AdSupport)
import AdSupport
#endif
```

Even if AdSupport is not linked to the project this macro will link it against the project.
You can reproduce this by creating a sample project using ATInternet Pod. If you inspect generated .app file with tools like *otool* you will see that the AdSupport framework is embed in ATInternet binary.

It's an issue for us because it look like that Apple has strengthened its privacy policy for Kids category app and reject submitted app from that category if it contains AdSupport framework even if it's not used in the app.

**Comment by nsagnett** [comment]
Hello, 

How do you import ATInternet Pod ? Without `use_frameworks!` directive ?

**Comment by sebbbbbb** [comment]
Hello,
I use the `use_frameworks!`directive. I tried without and i got the same issue.

**Comment by nsagnett** [comment]
Hello,

I just push a new branch `fix/adsupport` which solve issue. 
Can you try it ?

Regards,

**Comment by sebbbbbb** [comment]
Hello,
It work perfectly thanks for your help.
I have one question with this version : is the iOS12 min version required ? my project has iOS10.3 as min target SDK .

**Comment by nsagnett** [comment]
Yes absolutely, we will deploy a new feature which requires iOS 12 min !

**Comment by sebbbbbb** [comment]
Is it not possible to have a version with this fix and keep iOS10.3 as min target ?
I know i can stay in 2.18.0 but the 2.19.0 version was fixing an annoying bug with console logs...

**Comment by nsagnett** [comment]
It should be ok can you confirm everything is ok ?

**Comment by sebbbbbb** [comment]
Yes the only issue was the min SDK.

Thanks for support 👍
