### ISSUE TITLE
Crash on AppleWatch since 2.22.0

### ISSUE THREAD

**Issue by nimau** [at-internet/atinternet-apple-sdk#109]
Hi,

A crash appeared with version 2.22.0 on WatchOS

The following line of code is crashing on WatchOS:
Privacy.swift::getVisitorMode()
Line 109: Int(Date().timeIntervalSince1970) * 1000 
Swift runtime failure: arithmetic overflow

In fact there are 2 bugs on this line:
1. On WatchOS, Int is an Int32. You can use Int64 instead.
2. Int(Date().timeIntervalSince1970) * 1000  : you are loosing milliseconds

So it should be Int64(Date().timeIntervalSince1970 * 1000)

Note: in AVMedia.swift you are using Int(Date().timeIntervalSince1970 * 1000) which will also crash on WatchOS:
p Int(Date().timeIntervalSince1970 * 1000)
Fatal error: Double value cannot be converted to Int because the result would be greater than Int.max: file Swift/arm64_32-apple-watchos.swiftinterface, line 31211

Regards,
Nicolas.

**Comment by nsagnett** [comment]
Hi,

We just created a new branch with advised changes : https://github.com/at-internet/atinternet-apple-sdk/tree/fix/arithmetic_overflow_watchos

Can you try it ?

Regards

**Comment by nimau** [comment]
@nsagnett, it seems good, I've just tried on the watch and it's OK.

Thanks for your reactivity.

Regards

**Comment by nsagnett** [comment]
Hi, 

We released 2.22.3 version with fix on your issue 

Regards,
