### ISSUE TITLE
TrackerConfigurationKeys not available in Objective-C

### ISSUE THREAD

**Issue by fabb** [at-internet/atinternet-apple-sdk#11]
The documentation says:

> Samples to use constants (all constants are available in TrackerConfigurationKeys in Swift, prefixed by AT_CONF_ in Objective-C)

But this is actually not true since 2.5.0. Configuration keys like `AT_CONF_SITE` are not available in Objective-C.

Since Xcode 8, Objective-C supports class properties. So simply making `TrackerConfigurationKeys` inherit from `NSObject` would solve the issue:

```
public class TrackerConfigurationKeys: NSObject {
...
```

Objective -C code can now use the configuration keys with the same syntax like Swift:

```
TrackerConfigurationKeys.Site
```

**Comment by d-theo** [comment]
thanks for the feedback, it will be fixed in the next release ;)

**Comment by d-theo** [comment]
closing with the new release
