### ISSUE TITLE
[FeatureRequest]: SPM

### ISSUE THREAD

**Issue by aregler** [at-internet/atinternet-apple-sdk#110]
Hey AT Internet Team,

after all third party dependencies offer their frameworks via SPM, ATI is our last dependency that is still obtained via carthage. It would be great if you could also offer the ATI framework via SPM, so that we can drop carthage.
Do you think it would be possible?

Thank you, have a nice day and kind regards,

Arsatius

**Comment by BenDz** [comment]
Hey @aregler, please check my answer on the PR corresponding to this request: https://github.com/at-internet/atinternet-apple-sdk/pull/84#issuecomment-772395147
