### ISSUE TITLE
Where is 2.22.2?

### ISSUE THREAD

**Issue by markus-mohemian** [at-internet/atinternet-apple-sdk#112]
Hi, any reason why tag 2.22.2 has been deleted?
This actually broke our builds on CI. 
Shipping an updated version is fine, but removing existing tags is not.

**Comment by nsagnett** [comment]
Hi, 

Sorry for the inconvenience and for this agressive update but we found a very critical bug in some versions, 2.20.0 <= version <= 2.22.3 and we took the (heavy) decision to delete them to avoid customers issues

We strongly encourage you to upgrade to 2.22.3 asap

Regards,
