### ISSUE TITLE
Model not working on macOS

### ISSUE THREAD

**Issue by choli** [at-internet/atinternet-apple-sdk#113]
We have an app that is also running on macOS with the new Apple silicon macs. Unfortunately `utsname()`, which is used in TechnicalContext to decide which model the device is, does return iPad. Would it be possible to add an additional check like suggested in this topic? https://developer.apple.com/forums/thread/652667
Like that we could have a separate model for macOS users and therefore proper data.

**Comment by nsagnett** [comment]
You can submit a MR to be sure your use specific use case is cover like you want

**Comment by choli** [comment]
alright, in that case i close this issue. thanks
