### ISSUE TITLE
Compile error : Cannot find 'CTRadioAccessTechnologyNR'/'CTRadioAccessTechnologyNRNSA' in scope

### ISSUE THREAD

**Issue by nathsociete** [at-internet/atinternet-apple-sdk#115]
Hello,

I installed ATInternet-Apple-SDK/Tracker (2.23.0) on my project under Xcode Version 12.0 (12A7209), but i had a compile error in Tracker/TechnicalContext.swift, line 561

`
if #available(iOS 14.1, *) {
// These radio types are not available in iOS 14.0 and 14.0.1 (causes crashes) although it seems like they are
if rt == CTRadioAccessTechnologyNRNSA || rt == CTRadioAccessTechnologyNR {
return ConnexionType.fiveg
 }
 }
`

Cannot find 'CTRadioAccessTechnologyNR' in scope

Cannot find 'CTRadioAccessTechnologyNRNSA' in scope

Can you help ?

Thank you very much

**Comment by nsagnett** [comment]
Hello ! 

Unfortunately, your Xcode version is too old. It's the cause of your compilation issue

Regards,

**Comment by nathsociete** [comment]
Hello,

Thank you Nicolas for your help but unfortunately it does not work in the latest Xcode release Version 12.4 (12D4e)

Any other suggestion will be appreciate.

**Comment by nsagnett** [comment]
Hello ! 

Can you try it with the latest SDK version (2.23.1), #117 should be improve the code and fix your issue

Regards,

**Comment by nathsociete** [comment]
Hello,

At least the version 2.23.0 linked with the Xcode 12.5 beta.
After some tests, it appeared that there was a problem in my install of Xcode 12.4. I installed the version of Xcode 12.4 back again from the apple developper web site download page, and the problem disappeared.
I don't have any problem anymore with the 2.23.1.

Thank you.
