### ISSUE TITLE
Privacy.extendIncludeBuffer not working for at, ac parameters

### ISSUE THREAD

**Issue by MaximeLM** [at-internet/atinternet-apple-sdk#118]
Hello,

When using Privacy.extendIncludeBuffer to configure the exempt mode, the parameters *at* and *ac* are not sent, even when adding them to the include buffer. Other parameters like x17 and x18 are OK (verified with the debugger).

Sample code:
```
let tracker: Tracker = ATInternet.sharedInstance.defaultTracker
tracker.setSiteId(410501, sync: true, completionHandler: nil) // required
tracker.setLog("logp", sync: true, completionHandler: nil) // required
tracker.enableDebugger = true // track the hit sent
// tracker.delegate = trackerDelegate // verbose mode

// Configure exempt mode
Privacy.extendIncludeBuffer(.exempt, keys: "at", "ac", "x17", "x18")
Privacy.setVisitorMode(.exempt)
//Privacy.setVisitorMode(.optIn)

// Configure at, ac
tracker.identifiedVisitor.set("userId", visitorCategory: "status")

let screen = tracker.screens.add()

// Add x17, x18
screen.customVars.add(17, value: "custom_var_17", type: .app)
screen.customVars.add(18, value: "custom_var_18", type: .app)

screen.sendView() // send a screen hit
```

SDK version: 2.23.1

**Comment by nsagnett** [comment]
Hello ! 

Yes, it's a little bit tricky and different for at, an et ac parameters.

In fact, these parameters are linked with `persistIdentifiedVisitor` configuration, and it's true by default.
So, when this configuration is set to true, we want persist this kind of data in userDefaults. But, with privacy behaviour, if the storage not allowed IdentifiedVisitor data, parameters are not in userDefaults and after that, not injected in next hits.

To solve your issue, 2 possibilities : 
- Allow IdentifiedVisitor data in storage with exempt mode like this (recommended): 
```Privacy.extendIncludeStorage(visitorMode: "exempt", storageFeatureKeys: Privacy.StorageFeature.identifiedVisitor)```

- set `persistIdentifiedVisitor` configuration to false like this:
```tracker.setPersistentIdentifiedVisitorEnabled(false, sync: true, completionHandler: nil)```

Regards,

**Comment by MaximeLM** [comment]
That solved it, thank you!
