### ISSUE TITLE
Access didBecomeActive

### ISSUE THREAD

**Issue by choli** [at-internet/atinternet-apple-sdk#119]
We have the issue that we would like to send an event when coming back to the app. Unfortunately this is not possible being fired after the ApplicationDidBecomeActiveNotification that you use to update the session. Is it possible to send a tag after your LifeCycle handling? Thanks :)

**Comment by nsagnett** [comment]
Hello, 

I just created a branch called fix/lifecycle to your issue

When you catch applicationDidEnterForeground notification, you can call this new Tracker function:
```
tracker.applicationDidEnterForeground()
```
to enforce lifecycle computing at the good moment :)

**Comment by choli** [comment]
Very nice, works the way we would expect it to work.

**Comment by nsagnett** [comment]
Good news ! 

I will integrate in the future version, probably released next week

**Comment by nsagnett** [comment]
Hi, 

The fix has been integrated and available in 2.23.4 version

Regards,
