### ISSUE TITLE
Swift Package Manager integration

### ISSUE THREAD

**Issue by baptistedajon** [at-internet/atinternet-apple-sdk#135]
Hello Team,
Are you working on Swift Package Integration ? Because we try to avoid legacy dependencies manager.
Thanks :)

**Comment by BenDz** [comment]
Hello @baptistedajon 
We are about to release brand new SDK, with SPM support included.
The current one won't include it, for various technical reasons. You can however check this PR #114 with a fork offering the support.

**Comment by BenDz** [comment]
Hi @yalp, sorry for the delay.
Our new SDK has been released a few weeks ago! https://github.com/at-internet/piano-analytics-apple
