### ISSUE TITLE
SPM Support soon?

### ISSUE THREAD

**Issue by leobouilloux** [at-internet/atinternet-apple-sdk#138]
Hello, 

I was wondering if you could add SPM support in a future version. It'll be a nice addition alongside Cocoapods and Carthage installations. We are currently trying to migrate everything to SPM, and found a way to embed xcframeworks generated by Carthage in a swift package but it'll be better to have an official support.

Kind regards

**Comment by mickaelmalolepsy** [comment]
Hello, same here, we would appreciate SPM support. Thank you.
