### ISSUE TITLE
It's would be great if your project was part of Swift Source-Compatibility

### ISSUE THREAD

**Issue by mackoj** [at-internet/atinternet-apple-sdk#17]
https://swift.org/source-compatibility/#current-list-of-projects

**Comment by mackoj** [comment]
Is you code compatible with Swift 3.2 ?

**Comment by d-theo** [comment]
Not sure, the latest xCode version I have contains only swift 3.1
Does you or your company need it (and what about swift4) ?

**Comment by mackoj** [comment]
Xcode Beta 9 support Swift 3.2 which is Swift 4 Swift in swift 3 mode. Your code could have issues with this version of Swift. Before Migrating to Swift 4 your might need to move to Swift 3.2 and the **Swift Source-Compatibility** is here to guarantee that your code compiles under Swift 3.2. And prevent as much as it can source compatibility regression.

**Comment by mackoj** [comment]
http://www.jessesquires.com/blog/a-story-about-swift-source-compat/

**Comment by d-theo** [comment]
Thank you, we will take a look at this the next days 👍
The company plan (at the moment) is to provide swift3.2/4 compatibility mid august unless a client is asking for ;-)

**Comment by mackoj** [comment]
Where are you on this ? @d-theo

**Comment by d-theo** [comment]
I will try to take a look today to see how much time it needs to make it compatible

**Comment by d-theo** [comment]
I guess this can be really time consuming if we need to update the spm each time we commit on the repo

**Comment by mackoj** [comment]
Yes but it will guarantee that `atinternet-apple-sdk` work against new version of Swift...

**Comment by mackoj** [comment]
up ?
