### ISSUE TITLE
@available Versions Wrongly Used

### ISSUE THREAD

**Issue by fabb** [at-internet/atinternet-apple-sdk#18]
`@available` can be used to make a method/class only available to some version of the **target platform**. This lib uses it wrongly:

```
@available(*, deprecated: 2.5.0, message: "location is now only available as a screen object property.")
```

This makes the method available until `iOS 2.5.0`, `macOS 2.5.0` and `watchOS 2.5.0`. Probably not the intent here.

**Comment by d-theo** [comment]
Should be fixed
