### ISSUE TITLE
Need for Swizzling ?

### ISSUE THREAD

**Issue by mackoj** [at-internet/atinternet-apple-sdk#19]
Hi,

Why do you need to do Swizzling with JRSwizzle ?
You cannot assume that you are the only one to swizzle method in our app and when multiple SDK do swizzling it can become pretty ugly pretty fast.

```swift
try self.jr_swizzleMethod(#selector(UIRefreshControl.beginRefreshing), withMethod: #selector(UIRefreshControl.at_beginRefreshing))
try self.jr_swizzleMethod(#selector(UIView.init(frame:)), withMethod: #selector(UIRefreshControl.at_initWithFrame(_:)))
try self.jr_swizzleMethod(#selector(UIResponder.touchesEnded), withMethod: #selector(UISwitch.at_touchesEnded(_:withEvent:)))
try self.jr_swizzleMethod(#selector(UISwitch.at_touchesEnded(_:withEvent:)), withMethod: #selector(UIResponder.touchesEnded))
try self.jr_swizzleMethod(#selector(UIViewController.viewWillTransition(to:with:)), withMethod: #selector(UIViewController.at_viewWillTransitionToSize(_:withTransitionCoordinator:)))
try self.jr_swizzleMethod(#selector(UIViewController.viewDidAppear(_:)), withMethod: #selector(UIViewController.at_viewDidAppear(_:)))
try self.jr_swizzleMethod(#selector(UIApplication.sendEvent(_:)), withMethod: #selector(UIApplication.at_sendEvent(_:)))
try self.jr_swizzleMethod(#selector(UIApplication.at_sendEvent(_:)), withMethod: #selector(UIApplication.sendEvent(_:)))
```

Please consider providing an API to do what you did with swizzling?
Can we disable all swizzling in your SDK?
We really do not want any kind of swizzling in our app.

Thanks

**Comment by d-theo** [comment]
Hi,

The swizzling part is only active with the autotracking feature, eg if you enable one of the following :
```
tracker.enableLiveTagging = true;
tracker.enableAutotracking = true;
```

- LiveTagging allows you to configure your tagging plan here : https://livetagging.atinternet-solutions.com/#/
- Autotracking sends hit you configured via LiveTagging or sends page/click hits automatically

**Comment by mackoj** [comment]
Ok thanks we don't use autotracking feature.
