### ISSUE TITLE
Actual version infos

### ISSUE THREAD

**Issue by iGranDav** [at-internet/atinternet-apple-sdk#2]
Hi,

I opened a new issue regarding this new version real version number: https://github.com/at-internet/atinternet-ios-swift-sdk/issues/16

Any help would be appreciated.

Thanks

**Comment by fabb** [comment]
The versioning of this repo does not match the versioning of the documentation. As far as xiti support told me, the version 2.5.6 is the same as this repo's 1.0.7.

**Comment by d-theo** [comment]
yep that's true, we will make it right for the official smartsdk release
