### ISSUE TITLE
'ParamType' is not a member type of 'Param'

### ISSUE THREAD

**Issue by mackoj** [at-internet/atinternet-apple-sdk#20]
@d-theo I have this 93 issues with the last version of the SDK it does not build. Does the SDK run at least once in a CI before deployment?

`/ATInternet-Apple-SDK/ATInternetTracker/Sources/Tracker.swift:740:89: 'ParamType' is not a member type of 'Param'`

**Comment by d-theo** [comment]
which xCode version are you using ? Are you unable to compile the project ?

**Comment by mackoj** [comment]
I'm using Xcode Version 8.3.3 (8E3004b)

**Comment by d-theo** [comment]
We are not able to reproduce the problem, can you tell me how to reproduce it ?

**Comment by mackoj** [comment]
🤔 I have installed it through Cocoapods

**Comment by mackoj** [comment]
[BugAT.mp4.zip](https://github.com/at-internet/atinternet-apple-sdk/files/1165863/bug.at.mp4.zip)

**Comment by d-theo** [comment]
Hum we are not able to reproduce it on a vanilla project, could it be a type conflict with your code ?

**Comment by mackoj** [comment]
```

**Comment by mackoj** [comment]
/// Hit parameter
class Param: NSObject {
    /// Parameter key (Querystring variable)
    var key: String
    /// Parameter value
    var values: [(() -> String)]!
    /// Parameter options
    lazy var options: ParamOption? = ParamOption()
    /// Description (&p=v)
    var text: String {
        var str = "&\(key)="
        for val in self.values {
            str += "\(val()) "
        }
        return str
    }
    var isPersistent: Bool {
        return self.options?.persistent ?? false;
    }
    
    /**
    Default initializer
    
    - returns: a parameter with no key and no value
    */
    convenience override init() {
        self.init(key: "", value: {""});
    }
    
    /**
    Init a parameter with a key and a closure to execute as value
    
    - parameter key: of the parameter
    - parameter closure: to be executed by the hit builder
    
    - returns: a parameter
    */
    convenience init(key: String, value:@escaping () -> String) {
        self.init(key: key, value: value, options: nil);
    }
    
    /**
    Init a parameter with a key, a closure to execute as value and options
    
    - parameter key: of the parameter
    - parameter closure: to be executed by the hit builder
    - parameter options:
    
    - returns: a parameter
    */
    init(key: String, value:@escaping () -> String, options: ParamOption?) {
        self.key = key
        self.values = [value]
        super.init()
        self.options = options
    }
}
```

**Comment by mackoj** [comment]
Param don't seems to have an initializer with type `Param(key: key, value: value, type: type)` but it have one with option `init(key: String, value:@escaping () -> String, options: ParamOption?)` maybe it just a rename issue ?

**Comment by mackoj** [comment]
In my **Podfile.lock** I have 
```
  - ATInternet-Apple-SDK/SmartTracker (2.6.0):
    - JRSwizzle
    - KLCPopup
    - Socket.IO-Client-Swift
```

**Comment by d-theo** [comment]
That's very strange, we do have some documentation issue, but it's only noted as warning and ParamType is not even a project class

**Comment by mackoj** [comment]
<img width="377" alt="capture d ecran 2017-07-24 a 11 15 12" src="https://user-images.githubusercontent.com/661647/28516399-67d2b2e4-7061-11e7-8438-bd5c01d7add0.png">

**Comment by d-theo** [comment]
it looks like it's a cocoapod issue or something, to upload a project to cocoapods we have to compile it first... :/
If you are not using autotracking features, you can just import the tracker `ATInternet-Apple-SDK/Tracker, "~> 2.6.0"`

The last error states that "endPoint" is missing in a call, which is only called l.289 in Tracker.swift.
The file looks OK in the github side https://github.com/at-internet/atinternet-apple-sdk/blob/2.6.0/ATInternetTracker/Sources/Tracker.swift

**Comment by d-theo** [comment]
Can you compile it on a vanilla project like this one ? it just needs unzip/pod install
[sample.zip](https://github.com/at-internet/atinternet-apple-sdk/files/1169396/sample.zip)
(sorry for the random project naming)

if it compiles maybe you can try to
- delete your `Pods/` and `Podfile.lock`
- delete` Build/` and `DerivedData/`
- launch `pod install` again ?

**Comment by mackoj** [comment]
Maybe I don't have the good version of the files but it's strange...

**Comment by mackoj** [comment]
After deleting my Cocoapods local cache and reinstalling it, it worked.
It seems like the tag `2.6.0` has been modified after publication.

```
-> Installing ATInternet-Apple-SDK (2.6.0)
 > Git download
 > Git download
     $ /usr/bin/git clone https://github.com/at-internet/atinternet-apple-sdk.git /var/folders/p8/z55m7gfs4870s8_q15vks8840000gp/T/d20170724-8816-1wbos7l --template= --single-branch --depth 1 --branch 2.6.0
     Cloning into '/var/folders/p8/z55m7gfs4870s8_q15vks8840000gp/T/d20170724-8816-1wbos7l'...
     Note: checking out '728cf459cd085dab2d0ca4623ca3050903366093'.
     
     You are in 'detached HEAD' state. You can look around, make experimental
     changes and commit them, and you can discard any commits you make in this
     state without impacting any branches by performing another checkout.
     
     If you want to create a new branch to retain commits you create, you may
     do so (now or later) by using -b with the checkout command again. Example:
     
       git checkout -b <new-branch-name>
     
  > Copying ATInternet-Apple-SDK from `/Users/jmacko/Library/Caches/CocoaPods/Pods/Release/ATInternet-Apple-SDK/2.6.0-81f5e` to `Pods/ATInternet-Apple-SDK`
```
