### ISSUE TITLE
Problem with serialization with string of type "[8.8]" when preparing query

### ISSUE THREAD

**Issue by jdatour** [at-internet/atinternet-apple-sdk#21]
Hi,

![screen shot 2017-08-10 at 17 21 33](https://user-images.githubusercontent.com/20934201/29206512-89ff94e8-7e82-11e7-9503-8c437bd4a12e.png)

when serializing number such as "[8.8]", your method "parseJSON" in the class "Builder" returns any which is, I suspect, afterwise cast as Array of Float64 (or double) which results in transforming "8.8" to "8.80000000001"

Is it possible that you check the type of the serialized object in order to return the correct result ?

ty !

**Comment by mackoj** [comment]
@d-theo  I think transforming AppVersion to Double is not the good way to go what if your app version is 8.8.1 ?

**Comment by d-theo** [comment]
Hi, 
Could you please share your tag that produce this behavior ? The swift json parsing is not working as expected but it's going to be hard to work against the language. Maybe changing "[8.8]" to "["8.8"]" could solve temporary the issue ?

**Comment by jdatour** [comment]
The tag is "apvr". We did a temporary, quite ugly fix checking the type of the serialized object and mapping it, if possible, as an array of NSDecimal rounded. Using the appversion as String is, I think, the way to go but I don't know what are the implications in your code.

**Comment by jdatour** [comment]
Hi, any news on this issue ?

**Comment by mackoj** [comment]
@d-theo ?

**Comment by d-theo** [comment]
I going to investigate about the issue

**Comment by d-theo** [comment]
The workaround here is to change a line in in `Buffer.swift`
`applicationVersion = "[" + applicationVersion + "]"`
by
`applicationVersion = "[\"" + applicationVersion + "\"]"`

The problem here is that json.parse([version]) should output "[version]" (String) but in this case the parser thinks it's an Array of Float, outputting [8.000001] ...

I will release a patch next week :)

**Comment by mackoj** [comment]
@d-theo thanks

**Comment by mackoj** [comment]
Please consider updating this issue when the update is available please.

**Comment by d-theo** [comment]
V2.8.1 should solve the issue :)

**Comment by gudavo** [comment]
hello, I have the same issue with a custom screen parameter with value `"[true]"` becoming `"[1]"`
