### ISSUE TITLE
Carthage Support

### ISSUE THREAD

**Issue by morgan-legal** [at-internet/atinternet-apple-sdk#22]
Hello,

When do you think Carthage support will be available ?

Thank you !

Best,
Morgan

**Comment by d-theo** [comment]
Hi, I will try to see today if I can do something about it

**Comment by morgan-legal** [comment]
Actually, on the developers website, section "integration of the SDK" you seam to give the possibility to integrate the SDK via carthage:

```
 github "at-internet/atinternet-apple-sdk" >=1.0
```

Maybe it's only the readme that's not up to date ?

**Comment by d-theo** [comment]
It was like 2 years ago, and I never tried it again, not sure if it still works 👍

**Comment by d-theo** [comment]
sorry for the double post, I tried it and I am not sure it's going to be usable because the project has many Schemes (tvOS, watchOS...) and Carthage seems to lack an option for compiling only 1 of them, meaning that it will take like 15-20min to fetch and compile everything every time you will `carthage update` your project

**Comment by morgan-legal** [comment]
Actually you can specify the platform:

```
carthage update --platform iOS
```

**Comment by d-theo** [comment]
We still have 3 schemes for iOS: Tracker (lite version), SmartTracker, and AppExtensionTracker

**Comment by morgan-legal** [comment]
I don't really see this as a problem. I added this to my cartfile:
```

```
And ran the command:
```
carthage update --platform iOS
```
As a result, in my Builds folder I can see the 3 different frameworks:
`SmartTracker.framework`,`Tracker.framework` and `TrackerExtension.framework`

I just need to import the one(s) that I need to my project and I'm good to go :-)

**Comment by d-theo** [comment]
I'm glad it's working 👍
I will add this to the readme
