### ISSUE TITLE
Argument for a subspec for ATInternet-Apple-SDK-SmartTracker.podspec

### ISSUE THREAD

**Issue by mackoj** [at-internet/atinternet-apple-sdk#23]
Hi @d-theo,

In order to reduce the size of our app, reduce the number of our dependencies and improve the pre-main loading of our app. Can you please consider make a subspec for `ATInternet-Apple-SDK-SmartTracker.podspec` that remove `JRSwizzle`,`KLCPopup` and `Socket.IO-Client-Swift` because we don't use feature related to these SDK.

We use ATInternet-Apple-SDK-SmartTracker in a very manual way so if we could have a subspec ATInternet-Apple-SDK-SmartTracker(Core) it would be awesome.

Thanks,

**Comment by d-theo** [comment]
Hi, 
Did you encountered issues with `pod "ATInternet-Apple-SDK/Tracker"` ? it is intended to be a 'lite' version with no extra dependencies. If you don't use 'LiveTagging' or AutoTracking feature you should have no change to do in your code

**Comment by mackoj** [comment]
I will try thanks @d-theo

**Comment by mackoj** [comment]
Thanks it's what I was looking for.
