### ISSUE TITLE
`UIApplication.shared.windows` accessed outside main thread

### ISSUE THREAD

**Issue by iGranDav** [at-internet/atinternet-apple-sdk#24]
Reopening the issue here, since this library is concerned not the old swift specific version.

for history :
https://github.com/at-internet/atinternet-ios-swift-sdk/issues/20

**Comment by d-theo** [comment]
ok, the fix is live. Should be working without the annoying warnings :)

**Comment by iGranDav** [comment]
I confirm that this working 👍 with the debugger enabled.
