### ISSUE TITLE
'characters' is deprecated: Please use String or Substring directly

### ISSUE THREAD

**Issue by Cen92** [at-internet/atinternet-apple-sdk#26]
Hi, 
In v2.8.5 there is a bunch of warnings saying:
`'characters' is deprecated: Please use String or Substring directly`
when a project is compiled with Swift 4. This is also affecting the watchOSTracker library. 

Could these warnings be fixed?

**Comment by d-theo** [comment]
hi,
sure, I was pretty lazy with the new Swift String/Substring api, but I will try to fix it this week 👍

**Comment by d-theo** [comment]
Should be fixed in 2.8.6 !
