### ISSUE TITLE
Dependency issue ?

### ISSUE THREAD

**Issue by mackoj** [at-internet/atinternet-apple-sdk#3]
Hi,

Can you add your open source dependencies in your Podspec ?
Because if my app has the same dependencies has your SDK it will conflict.

Dependencies :
- JRSwizzle
- KLCPopup
- Reachability
- SRWebSocket
- SwiftyJSON

Thanks,

**Comment by fabb** [comment]
Yes, this should be cleaned up.

@maintainers: Just remove the source files from the project, and adapt the `podpec` accordingly.

**Comment by d-theo** [comment]
We will, but only for JRSwizzle, KLCPopup and SRWebSocket.
Reachability is not that stable and we are using a custom version so we will rename it in ATReachability to avoid conflicts with host applications. Same for SwiftyJSON

**Comment by d-theo** [comment]
closing with the new release
