### ISSUE TITLE
Database path

### ISSUE THREAD

**Issue by florentmorin** [at-internet/atinternet-apple-sdk#31]
Currently, except for tvOS, database path is document directory.

But documents are automatically stored for iCloud backup.

And it's not really secured. Especially with GDPR requirements.

Is it possible to use:
- custom path?
- cache path for everyone?

Thanks.

**Comment by d-theo** [comment]
Hi,

We will definitely consider your demand and update the ticket in the next few days :)

**Comment by florentmorin** [comment]
Yes, but I want to be able to store it in security group. It's secured and if I want to sync with widget it's possible.

I want the database to be really secured.

**Comment by d-theo** [comment]
Hello again,
GDPR only requires a user specification regarding the storage of his data outside the EU (iCloud). If the user asks for it not to be shared we will provide a method to prevent this from happening.

However configuring the database path is a more complex feature request and we need to study this need before doing it so we will first work on the compliancy with the GDPR and then we will see if we can modify our SDK so the path can be handled by our customers directly.
Finally even if the SDK is stored on Github, it's better to follow the standard process, sending a ticket to the AT Internet Support Team (you can contact them via your interface or to the mail support@atinternet.com if you don't have access to our interface). Our consultants can more freely discuss about it and include the concerned product experts to potentially push a story into our backlog and in addition to that we guarantee an answer in under 24h plus the estimated time they deliver an answer is two hours.

Regards

**Comment by florentmorin** [comment]
CHAPTER II, Article 5, (f) :

> Personal data shall be: [...] processed in a manner that ensures appropriate security of the personal data [...] using appropriate technical or organisational measures
--

Section 2, Article 32 (Security of processing), 1. (a) :

> the pseudonymisation and encryption of personal data
--

Contacting support.

Regards

**Comment by BenDz** [comment]
Hello,
After further talks with our DPO, there is no need to encrypt the data in our case.
However, we will add the ability to modify the storage path in order to let you change it.

Regards,
Benjamin, Product Owner

**Comment by d-theo** [comment]
Hello @florentmorin,
we pushed a version (2.9.3) with the ability to modify the database path : you can change the variable
`ATInternet.databaseDirectory: URL` at the beginning of your app (or wherever you want as it is before an offline event could happen).
Let us know if it works for you

Regards

**Comment by florentmorin** [comment]
Perfect. Thank you.
