### ISSUE TITLE
Carthage support

### ISSUE THREAD

**Issue by RaimarT** [at-internet/atinternet-apple-sdk#32]
Carthage support was announced in October 2016 to be available soon. When can it be expected to be available?

**Comment by iOSMoonSand** [comment]
@RaimarT I used this page in the docs to install via carthage: https://developers.atinternet-solutions.com/apple-universal-en/getting-started-apple-universal-en/integration-of-the-swift-library-apple-universal-en/#using-carthage_7

**Comment by BenDz** [comment]
We indeed have added it to our online documentation a few months ago (thank you @iOSMoonSand ), and forgot to update the Readme.
This is now up to date.
