### ISSUE TITLE
podspec: add swift_version

### ISSUE THREAD

**Issue by fabb** [at-internet/atinternet-apple-sdk#33]
Please add the `swift_version` to you `podspec`. This is [new in CocoaPods 1.4.0](https://github.com/CocoaPods/CocoaPods/issues/7134#issuecomment-358442942). This allows a client project to use a different Swift compiler version, and the Xiti pod will be correctly compiled with its (older) Swift version.

**Comment by d-theo** [comment]
hello,
Thank you for your report, we pushed it, the file `.swift-version` is removed in favor of `swift_version` in the `podspec`
