### ISSUE TITLE
3 warnings in ATInternet SDK in current Xcode (9.4.1)

### ISSUE THREAD

**Issue by DimDL** [at-internet/atinternet-apple-sdk#34]
Step 1: Add the SDK to your Podfile:  `pod 'ATInternet-Apple-SDK/Tracker'`
Step 2: Build. Three warnings in the SDK source code itself :

1/ ATReachability.swift:201:42: Plaform condition appears to be testing for simulator environment; use 'targetEnvironment(simulator)' instead

```
    private var isRunningOnDevice: Bool = {
        #if (arch(i386) || arch(x86_64)) && os(iOS)
```

2/ TechnicalContext.swift:131:96: Using '!' in this location is deprecated and will be removed in a future release; consider changing this to '?' instead

     `typealias sharedManagerCType = @convention(c) (AnyObject, Selector) -> AnyObject!`

3/ Tracker.swift:644:49: 'doNotTrack' is deprecated: Use ATInternet.optOut instead
        `if(!LifeCycle.isInitialized && !Tracker.doNotTrack) {`

**Comment by DimDL** [comment]
Note: I suggest changing
```
@objc @available(*, deprecated, message: "Use ATInternet.optOut instead")
public class var doNotTrack: Bool {
```
to:
```
@available(*, deprecated, renamed: "optOut")
public class var doNotTrack: Bool {
```
To get the Fix-it for free

**Comment by DimDL** [comment]
Note 3: There is something weird with the deprecation notice for optOut and doNotTrack, one of the two should be removed:
```
    /// Disable user identification.
    @objc @available(*, deprecated, message: "Use ATInternet.optOut instead")
    public class var optOut: Bool {
    
    /// Disable user identification.
    @objc @available(*, deprecated, message: "Use ATInternet.optOut instead")
    public class var doNotTrack: Bool {
```

**Comment by d-theo** [comment]
Hi, thanks for your comments ! I suppressed the 3 warnings on the last version (2.9.5)

For the doNotTrack and optOut thing, note that it's no longer Tracker static properties but ATInternet ones as it makes more sens to our eyes to put global configurations in ATInternet class instead of Tracker... Resulting in a double depreciation ^^'
