### ISSUE TITLE
Is this SDK the one we should use ?

### ISSUE THREAD

**Issue by mackoj** [at-internet/atinternet-apple-sdk#4]
There is multiple version of your SDK: 
- the 2.5.0 on the website
- this one
- https://github.com/at-internet/atinternet-ios-objc-sdk
- https://github.com/at-internet/atinternet-ios-swift-sdk

What is the good version of your SDK because we are planning at my company to use your SDK.

**Comment by mackoj** [comment]
There is multiple version of your SDK: 
- the 2.5.0 on the website
- this one
- https://github.com/at-internet/atinternet-ios-objc-sdk
- https://github.com/at-internet/atinternet-ios-swift-sdk

What is the good version of your SDK because we are planning at my company to use your SDK.

**Comment by d-theo** [comment]
The "good" version is atinternet-apple-sdk which will implements the latest feature of the sdk (SmartSDK / LiveTagging)

The atinternet-ios-swift-sdk is stable but will not be updated anymore unless bug fixes
