### ISSUE TITLE
Using .enableAutoTracking = true prevents the app from going in background

### ISSUE THREAD

**Issue by L4grange** [at-internet/atinternet-apple-sdk#42]
Hello. My company is required to use this library for analytics and screen tracking purposes, and as I was profiling our app today, I've noticed that when ATInternet.sharedInstance.defaultTracker. enableAutoTracking is enabled (set to true), the app does not sleep when entering background.

I know this since I see that CPU usage does not fall to 0 when the app enters background, which is what iOS Apps normally do when they enter background (unless background app refresh is enabled, which is not enabled in our case).

Is this bug with the SDK? If this is a feature it should be documented very clearly since it is overriding the default iOS app behaviour that any developer expects from their apps.

For now I've disabled enableAutoTracking, since it was causing a lot of battery drain when our app was in the background. Thank you for your time.

P.S.: Tested using the latest release of this library through CocoaPods (ATInternet-Apple-SDK 2.11.2)

**Comment by L4grange** [comment]
Thank you for your reply, we have since removed the line of code. Please deprecate the method in the next release and also update the documentation to warn users not to use the feature. Thanks again for your fast reply, you may close this issue, although I believe it should be left open until the autoTracking feature is removed or properly deprecated.

**Comment by nsagnett** [comment]
Hi there ! 

Since 2.14.0 version, we definitely stop SmartTracker support, so enableAutoTracking has been removed

**Comment by L4grange** [comment]
Perfect. Thank you for the information!
