### ISSUE TITLE
Can't change broadcastMode in RichMedia

### ISSUE THREAD

**Issue by phix23** [at-internet/atinternet-apple-sdk#50]
The property broadcastMode in RichMedia.swift should be public so that it can be set from the application.

**Comment by nsagnett** [comment]
You should use subclass and not directly RichMedia (Audio, LiveAudio, Video, LiveVideo, Medium, LiveMedium). In each subclass, broadcastMode is set with good value

**Comment by phix23** [comment]
Thank you! However then this is inconsistent with the Android SDK. In [RichMedia.java](https://github.com/at-internet/atinternet-android-sdk/blob/master/ATMobileAnalytics/Tracker/src/main/java/com/atinternet/tracker/RichMedia.java#L231) setBroadcastMode should be internal as well.

**Comment by nsagnett** [comment]
You're right but it's not a problem though.

**Comment by nsagnett** [comment]
It's ok for you ?

**Comment by phix23** [comment]
My issue is resolved. Thank you!
