### ISSUE TITLE
Better Support for Swift 4.2

### ISSUE THREAD

**Issue by mackoj** [at-internet/atinternet-apple-sdk#54]
Hi,

I have issue with your SDK when using Swift 4.2.

Please consider testing it with `pod spec lint --allow-warnings --use-libraries --swift-version=4.2 --verbose ATInternet-Apple-SDK-Tracker.podspec` in order to be sure your SDK won't cause any issue when implemented in a app that support Swift 4.2.
Adding this test to your CI will help a lot.

Swift 5 is around the corner please prepare your SDK for it.

Thanks,

**Comment by mackoj** [comment]
@d-theo can you please give this a look ?

**Comment by nsagnett** [comment]
Hi ! 

Thanks for the feedback, i will remove all SmartTracker dependencies in next release and clean useless podspec files in same time.

PS: You should use ATInternet-Apple-SDK.podspec instead of ATInternet-Apple-SDK-Tracker.podscpec

**Comment by mackoj** [comment]
We don’t want smart tracker feature(we don’t want any third party swizzling in our codebase) we only need tracker feature and we need it to work against Swift 4.2/5 in library mode properly.

**Comment by d-theo** [comment]
@mackoj We are working on it, starting with cleaning the podspec and unused 3rd party libraries in order to secure deployments

**Comment by nsagnett** [comment]
Hi @mackoj ! 

It's ok now, you kept only one podspec with subspec and add lint in our CI
