### ISSUE TITLE
Memory issues with CustomVars and RichMedia

### ISSUE THREAD

**Issue by msmigowski** [at-internet/atinternet-apple-sdk#55]
Hallo,

I had two problems with cycles using this library:

1. In function `@objc public func sendPlay(dynamicRefreshConfiguration: [Int: Int])`, line with 
```
self.chronoRefresh = DynamicRefresher(configuration: config) {
            self.sendRefresh()
}
```
I think here should be [weak self] because this block retains `RichMedia` object, which has strong reference to `DynamicRefresher` object. 

2. In `CustomVars` class, `var screen: AbstractScreen!` is defined. I think it should be `weak var screen: AbstractScreen!`, otherwise we get leak because `CustomVars` is retaining `AbstractScreen` and vice verse. 

What do you think about it?

**Comment by nsagnett** [comment]
Hi

Thanks for the suggestions ! 

I add the first in the next release ! 
For the second one, are you sure the weak reference must be add in CustomVars class and not reverse (if I understand the documentation : https://docs.swift.org/swift-book/LanguageGuide/AutomaticReferenceCounting.html) ?

**Comment by msmigowski** [comment]
Due to second issue, I think you should decide where to put `weak`. It depends on your architecture.

**Comment by nsagnett** [comment]
OK I see, many thanks we are working on it

**Comment by nsagnett** [comment]
The 2.14.2 version has been released and fix memory leaks detected
Thanks for your help

Regards
