### ISSUE TITLE
Hardcoded Static framework

### ISSUE THREAD

**Issue by gdollardollar** [at-internet/atinternet-apple-sdk#57]
Hello!

We are trying to add the ATInternet SDK as a cocoapods dependency of one of our SDK and we can't because it specifies `static_framework = true` in its Podfile.

Is there any specific reason for this? The code is built from source so building a dynamic framework should not raise an issue?

Thanks!
Guillaume

**Comment by nsagnett** [comment]
Hi !
Can you comment "use_frameworks!" and open your project with xcworkspace instead of xcodeproj ?
I know it's ridiculous but it works for me

**Comment by gdollardollar** [comment]
Hello,
The problem is related to pod libraries and not the final project.

To reproduce you simply have to add the `
ATInternet-Apple-SDK/Tracker`dependency to a podspec. For Example, something like:

```
Pod::Spec.new do |s|
  s.name         = 'TestATinternet'
  s.version      = '0.1.0'

...

  s.static_framework = true

  s.source_files = 'TestATinternet/**/*.swift'
  s.dependency 'ATInternet-Apple-SDK/Tracker'
end
```

Works but only because it also forces the `s.static_framework = true`, which makes it impossible to have other Pods that depend on the `'ATInternet-Apple-SDK/Tracker` pod to be built as dynamic libraries.

I was just wondering if it was actually required?
Removing the `s.static_framework = true` from the [Podspec](https://github.com/at-internet/atinternet-apple-sdk/blob/master/ATInternet-Apple-SDK.podspec) would allow more flexibility for people that want to build libraries around yours.

Sorry if I was not clear at first,
Thanks for the help!
Guillaume

**Comment by nsagnett** [comment]
Okay, I see.

It was required with Cocoapods 1.5 (#30 )

Now, it's not so i remove it for the next release 

Many Thanks !

**Comment by gdollardollar** [comment]
Perfect! Thank you very much!

**Comment by nsagnett** [comment]
Hi there,

It's ok for that (ef1f48f), for you too ?

**Comment by gdollardollar** [comment]
That's perfect!
