### ISSUE TITLE
Do you plan to support SPM ?

### ISSUE THREAD

**Issue by mackoj** [at-internet/atinternet-apple-sdk#6]
Do you plan to support [Swift Package Manager](https://swift.org/package-manager/) ?

**Comment by d-theo** [comment]
It's not planned yet

**Comment by florentmorin** [comment]
Did you plan to support it for Xcode 11?

**Comment by nsagnett** [comment]
It's possible but I can't give U a release date. I reopen this issue to keep it in mind

**Comment by nsagnett** [comment]
The SPM support require single source type for the moment and our project contains some features which needed mixed language source, and we can't exclude files from the package so we can't support it for the moment

**Comment by ivan-pavlovic** [comment]
Any changes here?

**Comment by BenDz** [comment]
@ivan-pavlovic Please check our feedback in this other issue related to SPM https://github.com/at-internet/atinternet-apple-sdk/issues/138
