### ISSUE TITLE
Won't Build using Xcode 11

### ISSUE THREAD

**Issue by AF-rta** [at-internet/atinternet-apple-sdk#62]
Hi, in preparation of soon iOS 13 release I tried to build my app using Xcode Version 11.0 beta 5 (11M382q). I'm using cocoapods V.1.7.5 and ATInternet-Apple-SDK (2.14.4). When building I get the following compiler error:

`<module-includes>:1:9: note: in file included from <module-includes>:1:
#import "Headers/ATInternet-Apple-SDK-umbrella.h"`
`Pods/Target Support Files/ATInternet-Apple-SDK/ATInternet-Apple-SDK-umbrella.h:19:9: note: in file included from /Users/raimar/Xcode/faz-.net-ios/Der_Tag/Pods/Target Support Files/ATInternet-Apple-SDK/ATInternet-Apple-SDK-umbrella.h:19:
#import "watchOSTracker.h"`
`Pods/ATInternet-Apple-SDK/ATInternetTracker/Sources/watchOSTracker.h:24:9: error: 'WatchKit/WatchKit.h' file not found
#import <WatchKit/WatchKit.h>`
`<unknown>:0: error: could not build Objective-C module 'Tracker'`

Any help appreciated! Thanks for your support!

**Comment by sonicso** [comment]
Hi,

You may try with the last version of ATInternet-Apple-SDK (2.15.0), we included <TargetConditionals.h> in watchOSTracker header file to fix this issue.

**Comment by MrJre** [comment]
@sonicso what if I also need the app extensions? We're currently using `ATInternet-Apple-SDK-AppExtension` 2.13.0 and getting a similar error.

**Comment by nsagnett** [comment]
@MrJre ATInternet-Apple-SDK-AppExtension pod is deprecated. You have to use this pod with extension target : `ATInternet-Apple-SDK/AppExtension`

**Comment by MrJre** [comment]
I'm still having problems updating pods to integrate your SDKs.
* My app now uses `ATInternet-Apple-SDK/Tracker`
* My watch app uses `ATInternet-Apple-SDK/watchOSTracker`

My extensions use `ATInternet-Apple-SDK/AppExtension`, but I still get the `ld: framework not found WatchKit` error when building the extensions. Additionally there is this:
> Multiple targets match implicit dependency for linker flags '-framework Tracker'. Consider adding an explicit dependency on the intended target to resolve this ambiguity. (in target 'NOS' from project 'NOS')

Using version 2.15.1 of your framework. What am I overlooking?

**Comment by nsagnett** [comment]
Hi, 

With new releases, the problem still occurs ?

**Comment by MrJre** [comment]
Seems to build now, thats great. 
The only thing I'm still seeing is the multiple targets warnings:
```
Multiple targets match implicit dependency for linker flags '-framework Tracker'. Consider adding an explicit dependency on the intended target to resolve this ambiguity. (in target 'NOS' from project 'NOS')
```
I think `ATInternet-Apple-SDK-AppExtension` used to solve this issue, but you mentioned it was deprecated. Is there an other way to solve this?

**Comment by nathsociete** [comment]
Hello,

I try to replace in my Obj-C project the following pods :
pod 'ATInternet-iOS-ObjC-SDK/iOS', '~> 2.2.7'

pod 'ATInternet-iOS-ObjC-SDK/AppExtension', '~> 2.2.7’

With these ones : 
    pod 'ATInternet-Apple-SDK/Tracker',     '2.14.4'
    pod 'ATInternet-Apple-SDK/AppExtension' (or ATInternet-Apple-SDK-AppExt)

But i've got errors while building ATInternet-Apple-SDK :
Pods/ATInternet-Apple-SDK/ATInternetTracker/Sources/watchOSTracker.h:24:9: error: 'WatchKit/WatchKit.h' file not found
#import <WatchKit/WatchKit.h>

Any ideas how to procede ?

Thanks a lot

**Comment by nsagnett** [comment]
Hi, 

Can you try with 2.15.0 release ? There are some modifications about conditional imports
