### ISSUE TITLE
Expose sdkVersion

### ISSUE THREAD

**Issue by choli** [at-internet/atinternet-apple-sdk#63]
Is there a way to access the sdkVersion. I didn't find any so far.

If not, is there a reason, why it's not exposed for public access?

**Comment by BenDz** [comment]
Hey @choli, we currently don't expose it since it is a technical data, that shouldn't be used outside of the SDK.
Could you please tell us more about your use case?
Thanks

**Comment by choli** [comment]
Hey, in our app we use a system info page to present alldependencies' sdk version in an overview list, for ATInternet we have to update this manually and this can easily be forgotten and then not up to date. not ultra critical, but as this would be a small change i wanted to ask

**Comment by BenDz** [comment]
Make sense, we will ship it with our soon to be released SDK update.

**Comment by nsagnett** [comment]
Hi @choli, 

2.15.1 SDK version is released and expose sdkVersion property from tracker object

It's ok for U ?

**Comment by choli** [comment]
trop bien, merci.
Works like a charm
