### ISSUE TITLE
Obj-C project doesn't build 

### ISSUE THREAD

**Issue by normenster** [at-internet/atinternet-apple-sdk#65]
I have a obj-c project and tried to integrate the 2.15 Library or 2.15.1 library

- added with cocoa pods > doesn't work
- added tracker with Tracker.framework > doesn't work

It always shows this error:

<img width="1179" alt="Bildschirmfoto 2019-09-02 um 15 14 10" src="https://user-images.githubusercontent.com/1347907/64162558-d434c380-ce3f-11e9-9120-896e9cf2b1fc.png">

I've tried all guidelines on how to combine swift code with obj-c projects, but it just has no impact. Also it makes no difference if I use Xcode 11 or Xcode 10.3. Any suggestions?

**Comment by nsagnett** [comment]
After some tests, we have successfully create a sample for integration.

You can find it here : https://github.com/at-internet/atinternet-react-native-sample
