### ISSUE TITLE
Crash: EXC_BAD_ACCESS KERN_INVALID_ADDRESS

### ISSUE THREAD

**Issue by choli** [at-internet/atinternet-apple-sdk#66]
We see these two crashes in Crashlytics but we cannot reproduce them. Do you know where this is coming from, what we could change to fix it? Do you think they are not related even though the same crash reason?

`0Crashed: com.apple.main-threadEXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x0000000000000000 Raw Text`
`0 | libswiftCore.dylib | swift_isUniquelyReferenced_nonNull_native + 10`
`1 | App | <compiler-generated> line 0specialized Tracker.processSetParam(_:value:options:)`
`2 | App | Tracker.swift line 817specialized Tracker.setParam(_:value:options:) + 817`
`3 | App | <compiler-generated> line 0CustomVar.setParams()`
`4 | App | <compiler-generated> line 0AbstractScreen.setParams()`
`5 | App | <compiler-generated> line 0Dispatcher.dispatch(:)`
`6 | App | <compiler-generated> line 0AbstractScreen.sendView()`

and the second one:
`0Crashed: com.apple.main-threadEXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x0000000000000000 Raw Text`
`0 | App | <compiler-generated> line 0specialized Tracker.processSetParam(:value:options:)`
`1 | App | <compiler-generated> line 0specialized Tracker.handleNotStringParameterSetting(:value:options:)`
`2 | App | <compiler-generated> line 0Dispatcher.dispatch(:)`
`3 | App | <compiler-generated> line 0AbstractScreen.sendView()`

If you are interested in more information let me know.

**Comment by nsagnett** [comment]
Do you use same tracker instance over multiple threads ?

**Comment by choli** [comment]
Oh ok, thanks for the hint. Would that explain both issues? Why?

Case 1 is called on a background thread, while on the main thread could be using the tracker as well. (So we should just create different instances for different threads?)

Case 2 is called from the main thread and I don't see anything that is called from another thread at this moment.

**Comment by nsagnett** [comment]
By design, the tracker is not safe for concurrent use, sorry for that..

So, yes, you should create a new instance per thread

**Comment by nsagnett** [comment]
Hi, 

Does the workaround solve your problem ?

**Comment by choli** [comment]
Hey, we moved all ATInternet action on a separate queue and will find out soon, whether this helps. I will keep you posted beginning of next week.

**Comment by choli** [comment]
Ok, now, newest state: We moved everything on a ati queue:
`private static let atiQueue = DispatchQueue(label: "ati.helper.queue")`

then we initialize the tracker as follows:

```
static func setUp(environment: Environment) {
    ...
    self.atiQueue.sync {
        self.defaultTracker?.setSiteId(site.identifier, sync: false, completionHandler: nil)
    }
}

private static let defaultTracker: Tracker? = {
    guard let url = Bundle.main.url(forResource: "ATDefaultConfiguration", withExtension: "plist"),
        let data = try? Data(contentsOf: url),
        let propertyList = try? PropertyListSerialization.propertyList(from: data, format: nil),
        let configuration = propertyList as? [String: String]
        else {
            assertionFailure("Cannot create a tracker without its configuration. Make sure ATDefaultConfiguration.plist is in the application bundle.")
                return nil
        }
    return ATInternet.sharedInstance.tracker("ATDefaultTracker", configuration: configuration)
}()
```

and then later whenever we track something:
```
@objc static func register(_ event: TrackingPage, trackerOptions setUpTracker: ((Tracker) -> Void)? = nil, screenOptions setUpScreen: ((Screen) -> Void)? = nil) {
    assert(self.environment != nil, "Cannot log events without an environment. Did you forget to set it during application launch?")
    self.atiQueue.async {
        guard Environment.active.configuration == .release,
            let tracker = self.defaultTracker
            else { return }

        setUpTracker?(tracker)
        ...
        switch event.type {
        case .view:
            let screen = tracker.screens.add(name, chapter1: chapter, chapter2: subChapter, chapter3: subSubChapter)
            self.addAppCustomVars(for: event.page, to: screen)
            setUpScreen?(screen)
            screen.level2 = self.LEVEL_2
            screen.sendView()
        case .touch:
            let gesture = tracker.gestures.add(name, chapter1: chapter, chapter2: subChapter, chapter3: subSubChapter)
            gesture.level2 = self.LEVEL_2
            gesture.sendTouch()
        case .exit:
            let gesture = tracker.gestures.add(name, chapter1: chapter, chapter2: subChapter, chapter3: subSubChapter)
            gesture.level2 = self.LEVEL_2
            gesture.sendExit()
        }
    }
}
```

The crashes we have now are different than before, they look as follows:
```

#0Crashed: ati.helper.queue EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x0000000000000000
--
0 | App | <compiler-generated> line 0specialized Dictionary.subscript.getter
1 | App | <compiler-generated> line 0specialized Tracker.processSetParam(_:value:options:)
2 | App | <compiler-generated> line 0Dispatcher.dispatch(_:)
3 | App | <compiler-generated> line 0AbstractScreen.sendView()
4 | App | ATInternetHelper.swift line 212closure #1 in static ATInternetHelper.register(_:trackerOptions:screenOptions:) + 212
5 | App | <compiler-generated> line 0thunk for @escaping @callee_guaranteed () -> ()
```

This seems to be different, would you know whats happening here?
Thanks already

**Comment by nsagnett** [comment]
In the first snippet, you set a siteId in async mode. It can be dangerous if the tracker used just after, the configuration maybe not ready at this time.

Also, the register function call tagging code in async block, so the same tracker used by multiples threads and the problem still occurs.

If you change async by sync block, it should be better

Regards

**Comment by choli** [comment]
But i call it sync on said thread, i just don't do it on the main thread. Thats how i make sure, I use the same tracker instance only on one thread, as you recommended

**Comment by nsagnett** [comment]
Yes but in the SDK, `self.defaultTracker?.setSiteId(site.identifier, sync: false, completionHandler: nil)`, called like that, is async method, even if you call in sync mode, SDK provide asynchronous management and can cause issues like crash.
Change it to : `self.defaultTracker?.setSiteId(site.identifier, sync: true, completionHandler: nil)` and you can put it outside the atiQueue

**Comment by choli** [comment]
We always had sync:true on not production versions, so maybe thats why we didn't get any crash like this on our integration systems.

What I did:
- I left it inside the queue
- I put sync to true for all environments onSetId

My question though: Why is the default of sync set to false, if that leads to issues?

**Comment by nsagnett** [comment]
It was the behaviour when the first version released, so to offer a full backward compatibility, we needed to keep this behaviour by default

**Comment by choli** [comment]
Thanks a lot, this seems to have solved this problem!
