### ISSUE TITLE
Expose applicationVersion 

### ISSUE THREAD

**Issue by fruitcoder** [at-internet/atinternet-apple-sdk#68]
We would like to override the `applicationVersion` to provide a custom String since the Dashboard is not consistent with the Android version. Currently the value is just pulled from the Bundle's `CFBundleShortVersionString`

https://github.com/at-internet/atinternet-apple-sdk/blob/e8019df69c0402f2317ea303aeef48025058feec/ATInternetTracker/Sources/TechnicalContext.swift#L270

**Comment by BenDz** [comment]
Hey @fruitcoder, I'm not sure to understand your issue.
This property (`applicationVersion`) aims at giving the actuel application version, as it is exposed in stores for instance. Why should it be consistent with the Android version?
There is a chance of misunderstanding of the data available in our analysis if the app version we retrieve is different from the actual version.

Could you give us more details about which data you would like to send?
We can consider to allow this, but we must ensure that this won't create side-effect to customers overriding it.

Thanks!

**Comment by fruitcoder** [comment]
Sorry I was on vacation, thank you for your answer. Our Android version has the environment attached to the version number if it's not production (1.2.3-staging/dev). Also for internal reasons of our deployment pipeline our version number for non production builds is always 1.0 (I comment more on why if you want). Therefore, it would be quite helpful if we could provide the value for the version from the client side. If you default to the `CFBundleShortVersionString` the change won't have any influence on current users of the framework

**Comment by BenDz** [comment]
Thank you, we better understand your case.
We will allow this in the next release for each SDK. No ETA yet, as it will depend on other features release.
Best

**Comment by fruitcoder** [comment]
Thanks a lot :)

**Comment by fruitcoder** [comment]
Do you have an update on this?

**Comment by BenDz** [comment]
> Do you have an update on this?

We plan on releasing a new version today.
We keep you informed.

**Comment by BenDz** [comment]
@fruitcoder v2.16.0 is now available and allow you to set a custom application version!
