### ISSUE TITLE
EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x0000000000000000

### ISSUE THREAD

**Issue by TICKME** [at-internet/atinternet-apple-sdk#69]
Crashed: com.apple.main-thread
EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x0000000000000000

Crashed: com.apple.main-thread
0  Tracker                        0x104f57a9c $s7Tracker9LifeCycleC25sessionBackgroundDurationySiSDyS2SGFZTf4nd_n + 32
1  Tracker                        0x104f590ac $s7Tracker9LifeCycleC17applicationActiveyySDyS2SGFZTf4nd_n + 148
2  Tracker                        0x104fbb400 $s7TrackerAAC17applicationActiveyyFTo + 132

We got this Error - cannot reproduce it ? Any Idea?

**Comment by nsagnett** [comment]
Do you use the same tracker instance in several threads ?
