### ISSUE TITLE
Confused Integrating SmartTracker

### ISSUE THREAD

**Issue by ogezue** [at-internet/atinternet-apple-sdk#7]
I tried to follow the documentation to integrate the SmartTracker SDK. Marketing sent me this config file that they loaded from your portal I suppose:

```
import SmartTracker

func application(application: UIApplication, didFinishLaunchingWithOptions launchOptions: [NSObject: AnyObject]?) -> Bool {
   let tracker = ATInternet.sharedInstance.defaultTracker

   // If SmartTracker is downloaded from Github, uncomment the line below in order to enable Live Tagging
   // tracker.token = "***secret***"

   // Enable live tagging for configuration (disable when going to production)
   tracker.enableLiveTagging = true

   // Enable auto tracking (disabled by default, enable auto tracking whenever you want)
   tracker.enableAutoTracking = false
   return true
}
```

So I assume I have to import SmartTracker. I do this with cocoapods and copied this line from your docs:  pod "ATInternet-Apple-SDK/SmartTracker",">=1.0"

The library gets integrated, but it states 102 warings. For example 
`/ATInternet-iOS-Swift-SDK/ATInternet-iOS-Swift-SDK-umbrella.h: warning: Missing file: /Pods/Target Support Files/ATInternet-iOS-Swift-SDK/ATInternet-iOS-Swift-SDK-umbrella.h is missing from working copy`

And it can't find SmartTracker on import.

Can you make sure that your documentation is up to date please? What do I have to import to use the smart tracker sdk?

And is it really necessary to disable ATS for your domain?

**Comment by d-theo** [comment]
Using Cocoapods you have to `import Tracker` (instead of SmartTracker if you download if from TagComposer). We will update the doc asap.

For the warnings i'm a bit confused because it looks like warnings from a different framework

**Comment by ogezue** [comment]
Thanks for help. Can you please give me the correct cocoapods statement?
The warnings have their origin in your framework - but I assume it has to to with the cocoapod import

**Comment by d-theo** [comment]
I just tried and took the one you posted 
`pod "ATInternet-Apple-SDK/SmartTracker",">=1.0"`
The last version is 1.0.6 (I had to type `pod update` from some reason because `pod install` was using the cache)

**Comment by ogezue** [comment]
```
Analyzing dependencies
Downloading dependencies
Installing ATInternet-Apple-SDK 1.0.6 (was 1.0.6)
```
--> success

but:
102 missing files:

- /ATInternet-iOS-Swift-SDK-dummy.m is missing from working copy
- /ATInternet-iOS-Swift-SDK/ATInternet-iOS-Swift-SDK.modulemap is missing from working copy
- /ATInternet-iOS-Swift-SDK/ATInternet-iOS-Swift-SDK-umbrella.h is missing from working copy
- /ATInternet-iOS-Swift-SDK/Tracker/Tracker/Video.swift is missing from working copy
....

Here is how I try to integrate your SDK:


```
import Tracker

class AnalyticsWrapper: NSObject {
    
    var tracker : Tracker?

    func setupTracker(){
    
        tracker = ATInternet.sharedInstance.defaultTracker
        if var tracker = self.tracker{
            tracker.token = "***secret***"
            // Enable live tagging for configuration (disable when going to production)
            tracker.enableLiveTagging = true
            
            // Enable auto tracking (disabled by default, enable auto tracking whenever you want)
            tracker.enableAutoTracking = false
        }
    }
    
    func trackEvent(event: String){
        print("trackEvent not implemented")
    }
    
}
```

It can't find any property that is listed above..

I usually write a wrapper class around the analytics libs to get more flexibility if anything changes.

**Comment by d-theo** [comment]
the mistake is tricky here 

```
import Tracker

class AnalyticsWrapper: NSObject {
    
    var tracker : AutoTracker? // AutoTracker is a subclass allowing auto tracking without breaking Tracker's API

    func setupTracker(){
```

**Comment by ogezue** [comment]
Yes - it did. Thank you very much!
Any idea about the missing files? Do you need more info?
The ATS-rule is still needed? There is no warning in the console.

**Comment by d-theo** [comment]
The ATS rule still exist unless you have a secure log to configure the tracker.
The missing files thing is very strange indeed, I think it's a strange issue with the new Git integration. If you remove the .git directory i believe the warning are not here anymore ?

**Comment by ogezue** [comment]
To remove the git directory is no option for us as we need our history. We use external git-Clients, not the one from XCode.
Is there anything we can to with the secure log? What if Apple stops supporting insecure connections?

**Comment by d-theo** [comment]
> Is there anything we can to with the secure log?

I think you have to ask your Marketing guy to get a secure log. You can configure the tracker to use it by the code or by editing the DefaultConfiguration files in Pods/ATInternet-Apple-SDK/SmartTracker/Resources/

**Comment by d-theo** [comment]
Any update ? Did you manage to make it work ?

**Comment by ogezue** [comment]
Yes thank you! No problems so far.
