### ISSUE TITLE
EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x0000000000000000

### ISSUE THREAD

**Issue by TICKME** [at-internet/atinternet-apple-sdk#70]
Crashed: com.apple.main-thread
0  Tracker                        0x1070b7504 $s7TrackerAAC15processSetParam33_D4E886A82F48D5FF6D01201C89A6EB9ELL_5value7optionsySS_SSycAA0D6OptionCtFTf4xnnn_n + 2012
1  Tracker                        0x107035b04 $s7Tracker10DispatcherC8dispatchyySayAA14BusinessObjectCGSgF + 6068
2  Tracker                        0x10707ab68 $s7Tracker14AbstractScreenC8sendViewyyF + 288
3  Tracker                        0x10707abac $s7Tracker14AbstractScreenC8sendViewyyFTo + 24

Cannot reproduce it - any idea ?

**Comment by nsagnett** [comment]
Do you use the same tracker instance in several threads ?
