### ISSUE TITLE
Resources included are different between CocoaPods and Carthage

### ISSUE THREAD

**Issue by MaximeLM** [at-internet/atinternet-apple-sdk#73]
When integrating ATInternet with CocoaPods for an iOS project, the following resources are included in the framework (use_frameworks!) or the app bundle (use_modular_headers!):

- core.manifest.json
- DefaultConfiguration.plist
- DefaultConfiguration~ipad.plist
- DefaultConfiguration~iphone.plist
- DefaultConfiguration~ipod.plist
- Info-iOS.plist
- Info-iOS-Extension.plist
- Info-tvOS.plist
- Info-watchOS.plist
- nuggad.manifest.json
- referential.json
- TrackerBundle.bundle

When building the framework with Carthage, the following resources are included in the framework:

- DefaultConfiguration.plist
- DefaultConfiguration~ipad.plist
- DefaultConfiguration~iphone.plist
- DefaultConfiguration~ipod.plist
- TrackerBundle.bundle

The \*.json and Info-\*.plist files don't seem to be used by the library.

When using use_modular_headers! in the podfile, these files are included in the app bundle and could cause conflicts.

**Comment by nsagnett** [comment]
The *.json and Info-*.plist are useless, that's right.

We will remove them for CocoaPods deployments in a future release, is it blocking for you at the moment ?

**Comment by MaximeLM** [comment]
No emergency. Thanks!

**Comment by nsagnett** [comment]
Hi there, 

2.16.1 is available with modifications 

Thanks !
