### ISSUE TITLE
ITMS-90809: Deprecated API Usage - UIWebView

### ISSUE THREAD

**Issue by MaximeLM** [at-internet/atinternet-apple-sdk#77]
We are receiving this warning when uploading our apps to AppStore Connect:

> We identified one or more issues with a recent delivery for your app, APP_NAME. Your delivery was successful, but you may wish to correct the following issues in your next delivery:
> 
> ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview for more information.
> 
> After you’ve corrected the issues, you can use Xcode or Application Loader to upload a new binary to App Store Connect.

ATInternet Tracker is using UIWebView in https://github.com/at-internet/atinternet-apple-sdk/blob/master/ATInternetTracker/Sources/TechnicalContext.swift

The App Store will no longer accept new apps using UIWebView as of April 2020 and app updates using UIWebView as of December 2020 : https://developer.apple.com/news/?id=12232019b

**Comment by nsagnett** [comment]
Thanks for the feedback ! 

2.16.2 is available, WKWebView is used instead
