### ISSUE TITLE
problems when archiving app with dSYM / bcsymbolmap files

### ISSUE THREAD

**Issue by matthieugayon** [at-internet/atinternet-apple-sdk#8]
I cannot compile my application when I include the dSYM / bcsymbolmap files in a copy files build phase ( as documented here https://developers.atinternet-solutions.com/apple-universal-en/getting-started-apple-universal-en/integration-of-the-swift-library-apple-universal-en/) , it is constantly crashing after issuing the following error ( see screenshot ) : 

<img width="1369" alt="screen shot 2017-02-24 at 17 51 19" src="https://cloud.githubusercontent.com/assets/3694172/23312538/6fef6412-faba-11e6-98f3-94381c907e83.png">

I am using the swift based smartTracker.framework for devices

**Comment by d-theo** [comment]
Hi, 
Do you have the "Strip symbol during copy" to No ?
Are you using a third party app to symbolicate crashes ?

**Comment by matthieugayon** [comment]
Indeed it solved the pb , thanks !!!

**Comment by matthieugayon** [comment]
actually now I get this error when I try to upload the app on the appstore : 

Couldn't find platform family in Info.plist CFBundleSupportedPlatforms or Mach-O LC_VERSION_MIN for SmartTracker

**Comment by d-theo** [comment]
Looks like it happens when you are including the dSYM files in the bundle.
Didn't go for full submission but it works with this configuration : 
![screenshot](https://cloud.githubusercontent.com/assets/14891777/23513601/d7ad6fb4-ff64-11e6-83a8-33c699c5f3ca.png)

**Comment by matthieugayon** [comment]
Thanks ! it did work !!! guess I can close that issue now :)

**Comment by d-theo** [comment]
You are welcome :)
