### ISSUE TITLE
Events in Debugger not visable in darkmode

### ISSUE THREAD

**Issue by af-ane** [at-internet/atinternet-apple-sdk#87]
Hey I found a problem where some texts of views are not visable in darkmode. The textcolor of the UILabel is not set so it adapts like it should to the darkmode and goes white.
But for every second rowView the backgroundColor get's specifically set to white so the text becomes invisable.

**Comment by nsagnett** [comment]
Yes absolutely, it will be fixed in the next release thanks !

**Comment by nsagnett** [comment]
Hi ! 

It's ok since 2.18.0, released today 

Regards
