### ISSUE TITLE
Carthage & Xcode 12

### ISSUE THREAD

**Issue by aregler** [at-internet/atinternet-apple-sdk#89]
Hi! In order to use the ATInternet SDK with Xcode 12 a raise of the minimum deployment target is necessary.
Is that planned in the near future? 

Also it would be great to get the framework via SPM. There's already a PR for that but somehow no further activity.
Thank you and kind regards,

Arsatius

**Comment by nsagnett** [comment]
Hi ! 

We just submit a new branch with Xcode 12 compatibility modifications, can you check your Carthage integration with this one ?

About SPM topic, unfortunately we have not planned yet to work on it for the moment

Regards,

**Comment by aregler** [comment]
Hi! Yep `feature/ios14` works 👍 thank you.
Well lacking support for SPM is a pity. ¯\_(ツ)_/¯
