### ISSUE TITLE
@discardableResult

### ISSUE THREAD

**Issue by fabb** [at-internet/atinternet-apple-sdk#9]
Many methods return a value that is rarely used at the call site. (e.g. `public func unset() -> Tracker`).

Right now the caller has to silence the warning by assigning it to an unused variable:
```
Swift:
_ = tracker.identifiedVisitor.unset()

Objective-C:
__unused Tracker *t = [tracker.identifiedVisitor unset];
```

It would be helpful to annotate such methods with `@discardableResult`. Then the caller does not get a warning/error if the variable is not assigned to a variable.

**Comment by d-theo** [comment]
Good point, we will try to ship this to the next release :-)

**Comment by d-theo** [comment]
closing with the new release
