### ISSUE TITLE
BackgroundTask.swift

### ISSUE THREAD

**Issue by AlaeddineOuerteni** [at-internet/atinternet-apple-sdk#90]
<img width="1241" alt="Capture d’écran 2020-08-05 à 17 53 43" src="https://user-images.githubusercontent.com/5662358/89435158-ca4ccc00-d744-11ea-80f6-0299e9f22cc7.png">

**Comment by nsagnett** [comment]
Can you provide some input like calling code when the crash occurs to check ?

Regards

**Comment by Shah3r** [comment]
Hey,

It seems to come from there : 
<img width="1672" alt="Screen Shot 2020-08-20 at 11 46 02" src="https://user-images.githubusercontent.com/13964794/90758628-9b575e00-e2df-11ea-9b4a-3ffabdc2cbf8.png">

And one step before :
<img width="1527" alt="Screen Shot 2020-08-20 at 12 21 32" src="https://user-images.githubusercontent.com/13964794/90758722-be820d80-e2df-11ea-88d8-5da94d44a3d0.png">

Let us know if you need more info,
Thanks

**Comment by nsagnett** [comment]
Hi ! 

If you can provide the calling code, in your application just to check how the SDK is used

Thanks

**Comment by AlaeddineOuerteni** [comment]
`func send(_ chapters: ATInternetTags.Chapters) {
        addUniversalLinkCustomTag()
        
        _ = tracker.customObjects.add(Constants.customObjects)
        let chaptersSanitized = chapters.toArray()
        guard let lastchapterSanitized = chaptersSanitized.last else { return }
        
        let screen: Screen
        
        switch chaptersSanitized.count {
        case 1:
            screen = tracker.screens.add(lastchapterSanitized)
        case 2:
            screen = tracker.screens.add(lastchapterSanitized, chapter1: chaptersSanitized[0])
        case 3:
            screen = tracker.screens.add(lastchapterSanitized, chapter1: chaptersSanitized[0], chapter2: chaptersSanitized[1])
        case 4:
            screen = tracker.screens.add(lastchapterSanitized,
                                         chapter1: chaptersSanitized[0],
                                         chapter2: chaptersSanitized[1],
                                         chapter3: chaptersSanitized[2])
        default:
            return
        }
        
        if let indicators = chapters.indicators {
            screen.addAllCustomVars(indicators: indicators)
        }
        
        screen.level2 = chapters.level2.toID()
        screen.sendView()
    }`

**Comment by nsagnett** [comment]
We found an other report for this issue : #43 

So, the question still the same : do you use the same tracker instance in several threads ?
