### ISSUE TITLE
SwiftUI Support

### ISSUE THREAD

**Issue by mackoj** [at-internet/atinternet-apple-sdk#93]
Hi AT Team (@nsagnett @d-theo @BenDz),

We are in the process of rebuilding our app from the ground up and it's in SwiftUI.
It don't to be able to display the debugger.

Please consider improving the support for SwiftUI

Thanks.

**Comment by mackoj** [comment]
Sorry it did work with SwiftUI only on device. 

But it don’t support dark mode 😉

![A2EFFCC8-D8D2-4740-B79B-298924B2C1EA](https://user-images.githubusercontent.com/661647/92418637-d4f5e900-f168-11ea-818e-0dd7a7163209.jpeg)
![F6D805B1-A395-49C4-9AAA-11E7F293EFB7](https://user-images.githubusercontent.com/661647/92418638-d6271600-f168-11ea-8c11-0d2c713e0821.png)

**Comment by nsagnett** [comment]
Hi @mackoj 

It should be good since latest SDK version (2.18.0 : https://github.com/at-internet/atinternet-apple-sdk/commit/565a53d45131e1f63476539be8e0e68e8c3a4bb9#diff-c8952502cc0d232aed6b724072d6a9c0)

**Comment by mackoj** [comment]
Thanks I will try

**Comment by nsagnett** [comment]
Hi @mackoj !

Have you test with latest SDK version for this issue or not again ? 

Regards,

**Comment by mackoj** [comment]
Since we are using SPM I have to migrate the SDK to the SPM branch it's scheduled but not done for the moment.

**Comment by mackoj** [comment]
It's great with the last sdk even if we are using my SPM branch
