### ISSUE TITLE
Threading issue. EXC_BAD_ACCESS.

### ISSUE THREAD

**Issue by aregler** [at-internet/atinternet-apple-sdk#95]
Hi.
From time to time our app crashes on the first ViewController on viewDidAppear.

![image](https://user-images.githubusercontent.com/14072295/94018626-1a452800-fdb1-11ea-8940-a3d4ecc6e4aa.png)
![image](https://user-images.githubusercontent.com/14072295/94018672-23ce9000-fdb1-11ea-9f0a-1754a0eb0cb4.png)

Every ATI tracking event is dispatched on the same queue.

![image](https://user-images.githubusercontent.com/14072295/94018769-3ea10480-fdb1-11ea-9e96-247c076b6a5d.png)

Do you have any suggestions what i can do to fix this issue?
PS: We're using the latest framework version.

Thank you,

Arsatius

**Comment by nsagnett** [comment]
Hi,

I can see `async` usage to submit tracking event so, even if it's the only one queue, events from one tracker can be treated in different threads.

Unfortunately, the SDK is not thread-safe and `async` usage is not recommended 

Regards

**Comment by aregler** [comment]
So you're basically suggesting to change the queue dispatch method to `sync`? 😬

**Comment by nsagnett** [comment]
Unfortunately yes, it's the best workaround

**Comment by aregler** [comment]
Hi! I am sorry, but i have to reopen the issue.
I followed your advise and created a dedicated DispatchQueue for the tracker `private let atiQueue = DispatchQueue(label: "atiDispatch")
`.

Also every call is done synchronously.

![image](https://user-images.githubusercontent.com/14072295/94896433-c19b1c80-048d-11eb-8232-b22f24095b94.png)

![image](https://user-images.githubusercontent.com/14072295/94896458-d2e42900-048d-11eb-9e0a-4095d1f9ff6d.png)

![image](https://user-images.githubusercontent.com/14072295/94896474-db3c6400-048d-11eb-9731-20977366cb77.png)

Do you have any suggestion what i can do to prevent those kind of crashes?

**Comment by nsagnett** [comment]
After some searches, this kind of issue can be solved after a simple clean project..Have you tried it ?

**Comment by aregler** [comment]
Well temporarily yes. I will report back when the issue happens again (or still happens in our live env after the next release).
Have a nice weekend,

Arsatius

**Comment by aregler** [comment]
Hi @nsagnett. Unfortunately we still get lots of crashes and i feel that there is nothing more i can do.

![image](https://user-images.githubusercontent.com/14072295/96559107-e4fefd80-12bc-11eb-9eea-b53f10796be6.png)

![image](https://user-images.githubusercontent.com/14072295/96558809-7e79df80-12bc-11eb-9064-6e131e239021.png)

Our new version is out just a few days and the ATI framework is still the top reason for the crashes.

![image](https://user-images.githubusercontent.com/14072295/96559016-cb5db600-12bc-11eb-8c05-82681156d7cc.png)

Do you have any ideas?
We are on 2.19.0 currently.

**Comment by nsagnett** [comment]
Hi, 

When i see your code, I find `self.tracker.screens.add(event: event)`

But, we don't have any helper in our code at this time 🤔

**Comment by aregler** [comment]
Yep thats just a small extension:

![image](https://user-images.githubusercontent.com/14072295/96564581-a15bc200-12c3-11eb-958e-82dcb6027e49.png)

**Comment by nsagnett** [comment]
OK I see, 

Can you provide some more code calling the SDK like configuration set for example ?

Just with screenshot, it's difficult to help you

Regards

**Comment by aregler** [comment]
Sure. Here's some extracted and adjusted code, which i hope mirrors the original app behaviour as good as possible.
[Sample.zip](https://github.com/at-internet/atinternet-apple-sdk/files/5413690/Sample.zip)

**Comment by nsagnett** [comment]
in your _AnalyticsHandler.swift_ (sample project), you have multiples async init lines :
```
extension Tracker {
	convenience init(configuration: TrackingConfigurationType) {
		self.init()
		setDomain(configuration.domain, completionHandler: nil)
		setPixelPath(configuration.pixelPath, completionHandler: nil)
		setSecuredLog(configuration.secureLog, completionHandler: nil)
		setBackgroundTaskEnabled(true, completionHandler: nil)
		ATInternet.optOut = !configuration.isEnabled
	}
}
```
Can you try replacing their with the sync way:
```
extension Tracker {
	convenience init(configuration: TrackingConfigurationType) {
		self.init()
		setDomain(configuration.domain, sync:true, completionHandler: nil)
		setPixelPath(configuration.pixelPath, sync:true, completionHandler: nil)
		setSecuredLog(configuration.secureLog, sync:true, completionHandler: nil)
		setBackgroundTaskEnabled(true, sync:true, completionHandler: nil)
		ATInternet.optOut = !configuration.isEnabled
	}
}
```

Regards,

**Comment by aregler** [comment]
Yep i will try and report back.
