### ISSUE TITLE
Performance Issue when using the Debugger view

### ISSUE THREAD

**Issue by mackoj** [at-internet/atinternet-apple-sdk#98]
Hi,

When enabling the debugger the application become really slow.
The issue is with Debugger.swift file in the addEvent function.

```swift
        DispatchQueue.main.sync(execute: {
            self.addEventToList()
        })
```

The synchronisation between what the SDK is doing and the debugger should be less impactful on performance.

| description | image | 
| --- | --- |
| with debugger enable | ![Capture d’écran 2020-10-20 à 18 31 57](https://user-images.githubusercontent.com/661647/96698209-24951a80-138d-11eb-8bf8-cd80e07da7f5.png) |
| without debugger | ![Capture d’écran 2020-10-20 à 18 31 34](https://user-images.githubusercontent.com/661647/96698226-2828a180-138d-11eb-845a-cb001a36902e.png) |

**Comment by mackoj** [comment]
@nsagnett any idea when or if this will receive a fix ?

**Comment by nsagnett** [comment]
Hi,

I understand it's not user friendly but it's not critical and after checking the code, I think it's tricky to optimise it and it's just for debugger feature.

We have not planned yet any study for this case, sorry 

Regards,

**Comment by mackoj** [comment]
Thanks but this make the debugger unusable in our app. I guess we will use proxyman

**Comment by mackoj** [comment]
Putting a bot for stale ticket is funny knowing that most tickets take a lot more than 30 days to getting fixed 🤣
