### ISSUE TITLE
iOS App + App Extension, integration via cocoapods not working (Multiple commands produce Tracker.framework)

### ISSUE THREAD

**Issue by Heidan34** [at-internet/atinternet-apple-sdk#99]
Hello,

I'm having a critical build issue when importing both the iOS Tracker and AppExtension versions of the SDK for the same project. I'm using cocoapods and import the required pod for each target as mentioned in the readme.
The problem seems to be that both versions of the SDK produces the same module named "Tracker". Ideally, one should be named Tracker and the other TrackerExtension or something like that to prevent this problem. I seems that previously there was an other pod "ATInternet-Apple-SDK-TrackerExtension" made for that case. Unfortunatly, it doesn't seem to be available anymore... Did I miss something ?
 
Also the readme mentions module conflicts, asking us to "see below" but no more information is provided bellow.

The problem seems to happen only when I archive the project, it works when I build it to run on my device for some reason.

```
error: Multiple commands produce '/Users/vagrant/workspace/branch_feat_5.0.0_xiti_migration/build/Build/Intermediates.noindex/ArchiveIntermediates/PROJECTNAME/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/Tracker.framework':
1) Target 'ATInternet-Apple-SDK-AppExtension' has create directory command with output '/Users/vagrant/workspace/branch_feat_5.0.0_xiti_migration/build/Build/Intermediates.noindex/ArchiveIntermediates/PROJECTNAME/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/Tracker.framework'
2) Target 'ATInternet-Apple-SDK-Tracker' has create directory command with output '/Users/vagrant/workspace/branch_feat_5.0.0_xiti_migration/build/Build/Intermediates.noindex/ArchiveIntermediates/PROJECTNAME/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/Tracker.framework'
```
Regards,

**Comment by nsagnett** [comment]
Hi ! 

Can you try it without `use_frameworks!` instruction ? It can be the problem (https://github.com/CocoaPods/CocoaPods/issues/7155)

Regards,

**Comment by Heidan34** [comment]
> Hi !
> 
> Can you try it without `use_frameworks!` instruction ? It can be the problem ([CocoaPods/CocoaPods#7155](https://github.com/CocoaPods/CocoaPods/issues/7155))
> 
> Regards,

Hi Nicolas,

Thank you for your reply :)

I don't think I can do that since I need it for other dependencies and it applies for every pod. I tried to set the `use_framework!` **after** declaring the ATInternet pod for each target, but the result was the same, as I expected. Also, the readme seems to indicates to set `use_framework!` too.

 I think the solution would probably to set a different module-name for this AppExtension pod so it doesn't get in conflict with the main one. (Both named "Tracker")
This solution was probably the one chosen previously with the pod "ATInternet-Apple-SDK-TrackerExtension" that had a different module-name "TrackerExtension" instead of "Tracker". Though, this "ATInternet-Apple-SDK-TrackerExtension" seems to be deprecated since it's still in version 2.13.0 (!= 2.19.0). The fact that the readme says that we "could need to use another pod" seems to indicate that this was the solution that could make me avoir conflicts.
Also, the documentation on the ATInternet website also quotes this pod in the integration tutorial ([](https://cocoapods.org/pods/ATInternet-Apple-SDK-AppExtension))

Do you have any information about why this has been deprecated ?

Thanks in advance,

**Comment by nsagnett** [comment]
Before 2.13.0 version, we provide different pods for Tracker and Extension.
Since, we provide only one pod with multiples sub-targets to facilitate deployments and maintainability.

After some local tests, i can reproduce even if I provide 2 pod instead of 1
It seems to be Cocoapods issue again (https://github.com/CocoaPods/CocoaPods/issues/8206)

Regards,

**Comment by Heidan34** [comment]
I will investigate on the different workarounds in this thread. Thanks a lot for your help !
I'll link the solution here as soon as I find one (let's hope I do ;))

Regards,

**Comment by Heidan34** [comment]
Hi, 
none of the provided solutions in the thread seemed to work for my case.

Therefore, may I propose a solution that won't induce a lot of work from your team. I have made a fork of your project to test the solution, in this fork I created a secondary podspec only for the AppExtension submodule, making it the main module. This way I was able to access a separate pod named "ATInternet-Apple-SDK-AppExtension" using a different modulename : "TrackerExtension". This solved my problem as there were no more name conflicts between two frameworks during the archiving process. I just had to import the right tracker using an environment variable in files shared between my app and the extension using the Tracker.

I was also wondering if I could use the extension submodule only if I don't use the debugger and other methods inaccessible to app extensions. Though this would be a dirty solution too.

This is a workaround to a Cocoapods or Xcode issue, but since the issue hasn't been solved in years now, it might be coming handy for you customers with the same needs as we had.

For my needs I could just put this new [podspec](https://github.com/Heidan34/atinternet-apple-sdk/blob/master/ATInternet-Apple-SDK-AppExtension.podspec) in a private repository, updating it from time to time to match yours when a new version comes out, but I can also make a merge request of this file with an update of the readme including these informations if you want.

Regards,

**Comment by nsagnett** [comment]
Hi, 

I pushed a new branch which embed fix for your problem : https://github.com/at-internet/atinternet-apple-sdk/tree/fix/cocoapods_extension
Can you try it ? If it solve the issue, it will be reintegrate for the next release

Regards,

**Comment by Heidan34** [comment]
> Hi,
> 
> I pushed a new branch which embed fix for your problem : https://github.com/at-internet/atinternet-apple-sdk/tree/fix/cocoapods_extension
> Can you try it ? If it solve the issue, it will be reintegrate for the next release
> 
> Regards,

I was pretty sure I replied but I can’t see my reply anymore for some reason ^^
I have been using your fix for a month now and It works fine. In order for this issue to survive until merging for the next release, I am adding a comment now :)

**Comment by nsagnett** [comment]
Hello, 

The new version is available and a new pod has been deployed : ATInternet-Apple-SDK-AppExtension

Regards,
